spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ok
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false

  freemarker:
    cache: true
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    template-loader-path: classpath:/templates
    expose-session-attributes: false
    expose-request-attributes: false
    suffix: .ftl
    expose-spring-macro-helpers: false
    content-type: text/html
